formatter: "markdown table" # this is required
version: "0.17"
# header-from: ""
# footer-from: ""
recursive:
  enabled: false
  path: ""
sections:
  hide: []
  show: []

content: |-
  {{ .Requirements }}

  ## Usage
  Basic usage of this module is as follows:
  ```hcl
  module "example" {
    source = "<module-path>"
  {{- if .Module.RequiredInputs }}
  {{"\n"}}  # Required variables
    {{- range .Module.RequiredInputs }}
    {{ .Name }} =
    {{- end }}
    {{- end }}
  {{- if .Module.OptionalInputs }}
  {{"\n"}}  # Optional variables
    {{- range .Module.OptionalInputs }}
    {{ .Name }} ={{ .GetValue | printf " %s" }}
    {{- end }}
    {{- end }}
  }
  ```

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
output:
  file: readme.md
  mode: inject
  template: |-
    <!-- BEGIN_AUTOMATED_TF_DOCS_BLOCK -->
    {{ .Content }}
    <!-- END_AUTOMATED_TF_DOCS_BLOCK -->
output-values:
  enabled: false
  from: ""
sort:
  enabled: true
  by: name
settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
